site_name: "Единая экосистема проектов"
site_url: "https://plankconstanta.github.io/central-docs/"

use_directory_urls: false

theme:
  name: material
  language: ru
  custom_dir: null 
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy

plugins:
  - search
