name: Build Multirepo Docs

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  repository_dispatch:
    types: [update_docs]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

# Даем экшену явные права на публикацию в GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Разрешаем запускать только одну сборку одновременно, чтобы они не конфликтовали
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Central Docs
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-multirepo-plugin

      - name: Inject Token into Config
        run: |
          sed -i 's|https://github.com|https://${{ secrets.DOCS_TOKEN }}@://github.com|g' mkdocs.yml

      - name: Create Temporary Docs Dir
        run: mkdir -p temp_empty_docs

      # Собираем сайт во временную папку 'site' в корне раннера
      - name: Build Site
        run: mkdocs build --clean --site-dir site

      # Настраиваем окружение GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Загружаем скомпилированный HTML как артефакт Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site' # Указываем папку, где лежит готовый HTML

      # Публикуем артефакт на сайт
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
