name: Build Multirepo Docs

on:
  push:
    branches: [-main]
  workflow_dispatch: 
  repository_dispatch:
    types: [update_docs]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Central Docs
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run:  pip install mkdocs-material mkdocs-print-site-plugin

      # Самостоятельно скачиваем папки из ваших проектов в структуру документации
      - name: Fetch Repositories Documentation
        run: |
          mkdir -p docs/project-alpha
          
          # Скачиваем проект Альфа и забираем только его доки
          git clone https://${{ secrets.DOCS_TOKEN }}@github.com/plankconstanta/docgen alpha_repo
          cp -r alpha_repo/docs/* docs/project-alpha/
          

      - name: Build Site
        run: mkdocs build --clean --site-dir site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
